name: Samplex
on: workflow_dispatch
jobs:
  install-python:
    runs-on: windows-2022
    steps:
    - name: list packages
      shell: pwsh
      run: |
        $gtx=Get-ItemProperty -Path "HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*", "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*", "HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*" |where { $_.DisplayName -ne $null } | Select-Object DisplayName, DisplayVersion, InstallDate
        $gtx
