name: Samplex
on: workflow_dispatch
jobs:
  install-python:
    runs-on: windows-2022
    steps:
    - name : Install excel module
      shell: pwsh
      run: |
        Install-Module -Name ImportExcel -Force
        get-installedmodule
    - name: list packages
      shell: pwsh
      run: |
        $gtx=Get-ItemProperty -Path "HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*", "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*" | Where-Object { $_.DisplayName -ne $null } | Select-Object DisplayName, DisplayVersion, InstallDate | Sort-Object DisplayName
        $gtx
        $packages | Export-Excel -Path "InstalledPackages.xlsx" -TableName "InstalledPackages" -TableStyle "Medium2"
    - name: upload sheet to owner
      uses: actions/upload-artifact@v3
      with:
        name: InstalledPackages.xlsx
        path: InstalledPackages.xlsx
